### ISSUE TITLE
Triple Quoted Python Strings are not comments

### ISSUE THREAD

**Issue by pradyunsg** [juliotrigo/today-sublime-color-scheme#1]
Triple Quoted Python Strings are strings and should not be highlighted as comments but as strings.

While often used for documenting, they are not _just_ for documenting and are used in many other contexts as well... Please fix.

**Comment by juliotrigo** [comment]
Thank you for your comment. I will fix this as soon as possible.

**Comment by pradyunsg** [comment]
Cleaning up my personal issues list - closing this.
